<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\7.png" />
    <None Remove="Assets\cherry.png" />
    <None Remove="Assets\lemon.png" />
    <None Remove="Assets\orange.png" />
    <None Remove="Assets\star.png" />
    <None Remove="Assets\watermelon.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\7.png" />
    <Resource Include="Assets\cherry.png" />
    <Resource Include="Assets\grapes.png" />
    <Resource Include="Assets\lemon.png" />
    <Resource Include="Assets\orange.png" />
    <Resource Include="Assets\star.png" />
    <Resource Include="Assets\watermelon.png" />
  </ItemGroup>

</Project>
